config/routes.rb
RedditPodcast::Application.routes.draw do
  get "post/cast"
  get "post/list"
  get "post/show"

  get 'cast/:id' => 'post#cast', as: :cast
  get 'castDone/:id' => 'post#castDone', as: :castDone
  get 'show/:id' => 'post#show', as: :show

  root 'post#root'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
require "voice_bunny"

class PostController < ApplicationController
  def list
    @posts = reddit.front_page :category => :top, :time => :all
  end
  
  def show
    puts params
    @post = Post.find_by(redditId: params[:id])
    @link = reddit.link("t3_#{params[:id]}")
  end
  
  # request cast to voice bunny 
  def cast
    
    # retrieve link information
    @link = reddit.link("t3_#{params[:id]}")

    # request Speedy
    project = {
        script: @link.title,
        title: 'Reddit Podcast',
        #test: 1,
        ping: "#{request.protocol}#{request.host_with_port}/castDone/#{@link.id}",
        auditionScript: @link.title,
        maxEntries: 3,
        language: 'eng-us',
        genderAndAge: 'middleAgeMale',
        lifetime: 86400,
        remarks: 'I want a really friendly voice',
        syncedRecording: 1,
        price: 35
    }
    project = VoiceBunny.instance.addSpeedy(project)
    
    # save the project id in the post model
    if project
        @post = Post.new(redditId: @link.id, 
                vbProjectId: project["id"], 
                url: @link.url )
        @post.save
    end
    
    redirect_to :action => :show
  end
  
  # ping action from Voice Bunny Api, save the url of the read
  def castDone
        @post = Post.find_by(redditId: params[:id])
        project = VoiceBunny.instance.getProject(@post.vbProjectId)
        @post.vbReadUrl = project["reads"][0]["urls"]["part001"]["default"]
        @post.save
        render :status => 200
  end
  
  # Reedit client method
  def reddit
    if !@redditClient 
        @redditClient = RedditKit::Client.new 'fpadillao', 'tr1n1tar1a'
    end
    return @redditClient
  end
  
  def root 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditPodcast</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Reddit Podcast", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <!---li><%= link_to "Home",    '#' %></li>
              <li><%= link_to "Help",    '#' %></li>
              <li><%= link_to "Sign in", '#' %></li-->
            </ul>
          </nav>
        </div>
      </div>
    </header>

<div class="container">

<%= yield %>

</div>

<!--footer class="footer">
  <small>
    <a href="/"></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer-->

</body>
</html>

app/views/post/cast.html.erb
<% if @post.vbReadUrl %>
    <audio controls>
      <source src="<%= @post.vbReadUrl%>" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
    <iframe src="<%= @post.url %>" width="100%" height="800">
<% else %>
    <h1> Pending Cast</h1>
    <p><b>URL</b> @link.title</p>
<% end %>

app/views/post/list.html.erb
<h2>Reddit Front Page (All Time)</h2>

<div class="posts">
 <% @posts.each do |link| %>
    <div class="post">
      <%= link_to link.title, show_path(link.id) %> 
    </div>
 <% end %>
</div>

app/views/post/show.html.erb
<h1> Link Status</h1>

<div><%= link_to @link.title, @link.url %></div>

<% if !@post %>
        <p> This link has not read </p>
      <%= link_to "Cast on Voice Bunny!", cast_path(params[:id]), class: "btn btn-large btn-primary" %>
<% elsif @post.vbReadUrl %>
    <audio controls>
      <source src="<%= @post.vbReadUrl%>" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
    <iframe src="<%= @post.url %>" width="100%" height="800">
<% else %>
    <b>Pending Cast</b>
<% end %>